name: Test Telegram

on:
  workflow_dispatch:

jobs:
  test_telegram:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run test message
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python test_telegram.py
